// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8sJ0MbyBqIgGTsoKkDzaMtwBHXRzuECo',
    appId: '1:114257529600:android:9e818db91f62e524dc01e5',
    messagingSenderId: '114257529600',
    projectId: 'roomrental-20afd',
    storageBucket: 'roomrental-20afd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOg9MjEzNhrgqinO-Prp2KiU1fuAIfFaI',
    appId: '1:114257529600:ios:71a611992c6d4f05dc01e5',
    messagingSenderId: '114257529600',
    projectId: 'roomrental-20afd',
    storageBucket: 'roomrental-20afd.appspot.com',
    iosBundleId: 'com.example.roomRental',
  );
}
